dist: trusty
sudo: required
services: 
  - docker

language: go
# If you are adding any features that require a higher version of golang, such as golang 1.13 for example,
# please contact maintainers to check of the releasing systems can handle the newer versions.
go: "1.12"

jobs:
  include:
    # not working due to security restrictions on travis
    # secret env variables are not available for PR builds
    #- stage: build image
    #  name: "build image and push to quay.io/odo-dev/init-image-pr"
    #  script:
    #    - ./scripts/build-push-image.sh 

    # Run a few odo integration tests
    - stage: test
      name: "generic, login, component command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-generic
        - travis_wait make test-cmd-login-logout
        - travis_wait make test-cmd-cmp
        - odo logout

    - stage: test
      name: "preference, config, url and debug command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmd-pref-config
        - travis_wait make test-cmd-url
        - travis_wait make test-cmd-debug
        - odo logout

    - stage: test
      name: "service, link, component sub-commands command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh service-catalog
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmd-service
        - make test-cmd-link-unlink
        - travis_wait make test-cmd-cmp-sub
        - odo logout

    - stage: test
      name: "watch, storage, app, project, push, devfile catalog, devfile create, devfile push command integration tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-cmd-watch
        - travis_wait make test-cmd-storage
        - travis_wait make test-cmd-app
        - travis_wait make test-cmd-push
        - travis_wait make test-cmd-project
        - travis_wait make test-cmd-devfile-catalog
        - travis_wait make test-cmd-devfile-create
        - travis_wait make test-cmd-devfile-push
        - travis_wait make test-cmd-devfile-watch
        - odo logout

    - stage: test
      name: "core beta, java, source e2e tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make goget-tools
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-e2e-beta
        - travis_wait make test-e2e-java
        - travis_wait make test-e2e-source
        - travis_wait make test-e2e-images
        - odo logout
