dist: trusty
sudo: required
services: 
  - docker

language: go

jobs:
  include:
    - stage: test
      name: "Run odo e2e tests"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u system:admin
        - oc --request-timeout 5m import-image java --namespace=openshift --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:1.5 --confirm
        - oc annotate istag/java:latest --namespace openshift tags=builder --overwrite
        - oc login -u developer
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-e2e-scenarios
    # Run a few odo integration tests
    - stage: test
      name: "Run odo integration tests (generic, component, java)"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-generic
        - travis_wait make test-cmp-e2e
    - stage: test
      name: "Run odo integration tests (source, watch)"
      script:
        - ./scripts/testing.sh
        - cd $GOPATH/src/github.com/openshift/odo
        - ./scripts/oc-cluster.sh
        - oc login -u developer
        - make bin
        - sudo cp odo /usr/bin/odo
        - travis_wait make test-java-e2e
        - travis_wait make test-source-e2e
        - travis_wait make test-watch-e2e
